services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - '8080:8080'
      - '5001:5001'
    # environment:
    #   - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: chatapp-backend:latest
    ports:
      - '127.0.0.1:3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: chatapp-frontend:latest
    ports:
      - '3000:80'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
